<?php

namespace App\Enums;

enum NOTIFICATION_TYPE: string
{
    case AGENT_APPLICATION = 'AGENT_APPLICATION';
    case PROPERTY_STATUS_CHANGE = 'PROPERTY_STATUS_CHANGE';
    case NEW_PROPERTY_INQUIRY = 'NEW_PROPERTY_INQUIRY';
    case NEW_APPOINTMENT = 'NEW_APPOINTMENT';
    case SYSTEM_ALERT = 'SYSTEM_ALERT';
    case USER_ACCOUNT_UPDATE = 'USER_ACCOUNT_UPDATE';
}
